Repository octokit/auth-app.js, pull requests merged in 2021-04, with the labels that each got.

#278 docs(README): Updated Documentation for Repository ID's in Installation Authentication Section
  README.md
Labels: documentation, maintenance

#276 ci: add NodeJS v16 to test matrix
  .github/workflows/test.yml
Labels: maintenance

#279 feat(repositoryNames) Able to filter out what repos the Installation Token has access to via repo name
  README.md
  src/cache.ts
  src/get-installation-authentication.ts
  src/to-token-authentication.ts
  src/types.ts
  test/index.test.ts
Labels: feature
