Repository octokit/auth-app.js, pull requests merged in 2021-06, with the labels that each got.

#296 feat: set `error.response`
  package-lock.json
  package.json
  src/hook.ts
Labels: feature

#300 fix: Do not intercept auth.hook(request, "POST https://github.com/login/oauth/access_token") requests
  src/hook.ts
  test/index.test.ts
Labels: bug

#301 fix(typescript): corret types for `auth({ type: "installation", installationId, factory })`
  src/types.ts
Labels: bug, typescript

#285 fix: add webhook deliveries APIs
  src/requires-app-auth.ts
Labels: feature
