Repository octokit/auth-app.js, pull requests merged in 2021-02, with the labels that each got.

#242 docs(README): add note on graduated `machine-man` preview
  README.md
Labels: documentation, maintenance

#249 feat(auth): throw Error when auth type is not a valid one
  src/auth.ts
  test/index.test.ts
Labels: feature

#255 fix: remove `scopes` from API as OAuth scopes are not supported by GitHub Apps, OAuth tokens inherit the installtion permissions instead
  README.md
  src/get-app-authentication.ts
  src/get-oauth-authentication.ts
  src/index.ts
  src/types.ts
  test/deprecations.test.ts
  test/index.test.ts
Labels: bug
