Repository octokit/auth-app.js, pull requests merged in 2023-05, with the labels that each got.

#460 fix: `requiresAppAuth` was matching unintended URLs.
  src/requires-app-auth.ts
  test/index.test.ts
Labels: Type: Bug

#475 fix(build): add script to fix `package.json` before publishing
  .github/workflows/release.yml
  scripts/fix-package-json.js
Labels: Type: Maintenance, Priority: High

#479 fix(build): replace Pika with esbuild and tsc
  .github/workflows/release.yml
  package-lock.json
  package.json
  scripts/build.mjs
  scripts/fix-package-json.js
  test/index.test.ts
  tsconfig.json
Labels: Type: Maintenance

#480 fix(typescript): mark imports/exports that are only used for types explicitely
  src/auth.ts
  src/cache.ts
  src/get-app-authentication.ts
  src/get-installation-authentication.ts
  src/hook.ts
  src/index.ts
  src/to-token-authentication.ts
Labels: Type: Maintenance
